language: cpp
sudo: false

os: linux
dist: xenial
compiler:
  - clang
  - gcc
env:
  global:
    - MAKEFLAGS="-j2"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
  - make gtestrun
  - make run
